const TABLE_DATA = {
  SET_COUNTRY_INFO: "GET_COUNTRY_INFO",
  SET_COORDINATES: "SET_COORDINATES",
  SET_ZOOM: "SET_ZOOM",
  SET_MAP_COUNTRY: "SET_MAP_COUNTRY",
  SET_CASES_TYPE: "SET_CASES_TYPE",
};

export default TABLE_DATA;
